### Q1. Load and Explore the Dataset

Load the `AirQalityDataset.csv` file into a pandas DataFrame using the correct separator.

After loading the data:

1. Display basic information about the dataset.
2. Save the statistical description of the dataset into a separate variable.
3. Drop fully empty/unnamed columns, and rows
4. Use `type()` to print the type of that description variable.

In [1]:
# your Code Here
import numpy as np
import pandas as pd


df = pd.read_csv('AirQualityDataset.csv', sep=None, engine='python')

display(df.head())         
print(df.shape)             
df.info()                  

desc = df.describe(include='all')
display(desc)

df = (df.loc[:, ~df.columns.str.contains(r'^Unnamed', na=False)]
        .dropna(axis=1, how='all')
        .dropna(axis=0, how='all'))

print(type(desc))  


Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0  10/03/2004  18.00.00     2.6       1360.0     150.0      11.9   
1  10/03/2004  19.00.00     2.0       1292.0     112.0       9.4   
2  10/03/2004  20.00.00     2.2       1402.0      88.0       9.0   
3  10/03/2004  21.00.00     2.2       1376.0      80.0       9.2   
4  10/03/2004  22.00.00     1.6       1272.0      51.0       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0         1046.0    166.0        1056.0    113.0        1692.0       1268.0   
1          955.0    103.0        1174.0     92.0        1559.0        972.0   
2          939.0    131.0        1140.0    114.0        1555.0       1074.0   
3          948.0    172.0        1092.0    122.0        1584.0       1203.0   
4          836.0    131.0        1205.0    116.0        1490.0       1110.0   

      T    RH      AH  Unnamed: 15  Unnamed: 16  
0  13.6  48.9  0.7578          NaN          NaN  
1  13.3  47.7  0.7255          NaN          NaN  
2  11.9  54.0  0.7502          NaN          NaN  
3  11.0  60.0  0.7867          NaN          NaN  
4  11.2  59.6  0.7888          NaN          NaN

(9471, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Date           9357 non-null   object 
 1   Time           9357 non-null   object 
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   float64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
 15  Unnamed: 15    0 non-null      float64
 16  Unnamed: 16    0 non-null      float64
dtypes: float64(15), object(2)
memory usage: 1

Date      Time       CO(GT)  PT08.S1(CO)     NMHC(GT)  \
count         9357      9357  9357.000000  9357.000000  9357.000000   
unique         391        24          NaN          NaN          NaN   
top     21/09/2004  18.00.00          NaN          NaN          NaN   
freq            24       390          NaN          NaN          NaN   
mean           NaN       NaN   -34.207524  1048.990061  -159.090093   
std            NaN       NaN    77.657170   329.832710   139.789093   
min            NaN       NaN  -200.000000  -200.000000  -200.000000   
25%            NaN       NaN     0.600000   921.000000  -200.000000   
50%            NaN       NaN     1.500000  1053.000000  -200.000000   
75%            NaN       NaN     2.600000  1221.000000  -200.000000   
max            NaN       NaN    11.900000  2040.000000  1189.000000   

           C6H6(GT)  PT08.S2(NMHC)      NOx(GT)  PT08.S3(NOx)      NO2(GT)  \
count   9357.000000    9357.000000  9357.000000   9357.000000  9357.000000   
unique          NaN            NaN          NaN           NaN          NaN   
top             NaN            NaN          NaN           NaN          NaN   
freq            NaN            NaN          NaN           NaN          NaN   
mean       1.865683     894.595276   168.616971    794.990168    58.148873   
std       41.380206     342.333252   257.433866    321.993552   126.940455   
min     -200.000000    -200.000000  -200.000000   -200.000000  -200.000000   
25%        4.000000     711.000000    50.000000    637.000000    53.000000   
50%        7.900000     895.000000   141.000000    794.000000    96.000000   
75%       13.600000    1105.000000   284.000000    960.000000   133.000000   
max       63.700000    2214.000000  1479.000000   2683.000000   340.000000   

        PT08.S4(NO2)  PT08.S5(O3)            T           RH           AH  \
count    9357.000000  9357.000000  9357.000000  9357.000000  9357.000000   
unique           NaN          NaN          NaN          NaN          NaN   
top              NaN          NaN          NaN          NaN          NaN   
freq             NaN          NaN          NaN          NaN          NaN   
mean     1391.479641   975.072032     9.778305    39.485380    -6.837604   
std       467.210125   456.938184    43.203623    51.216145    38.976670   
min      -200.000000  -200.000000  -200.000000  -200.000000  -200.000000   
25%      1185.000000   700.000000    10.900000    34.100000     0.692300   
50%      1446.000000   942.000000    17.200000    48.600000     0.976800   
75%      1662.000000  1255.000000    24.100000    61.900000     1.296200   
max      2775.000000  2523.000000    44.600000    88.700000     2.231000   

        Unnamed: 15  Unnamed: 16  
count           0.0          0.0  
unique          NaN          NaN  
top             NaN          NaN  
freq            NaN          NaN  
mean            NaN          NaN  
std             NaN          NaN  
min             NaN          NaN  
25%             NaN          NaN  
50%             NaN          NaN  
75%             NaN          NaN  
max             NaN          NaN

<class 'pandas.core.frame.DataFrame'>


### Q2. Dataset structure and features overview  
Write a code to collect:
1. The number of rows and columns in the dataset.
2. The list of first 10 feature columns excluding `'Date'` and `'Time'`.  

Store both lists in tuple called `dataset_info` and print it.

In [62]:
# your Code Here
import numpy as np
import pandas as pd

rows, cols = df.shape
feature_cols = df.columns.drop(['Date', 'Time'], errors='ignore')[:10].tolist()

dataset_info = ([rows, cols], feature_cols)
print(dataset_info)

([9357, 15], ['CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)'])


### Q3. CO(GT) summary with Pandas and NumPy
Compute the **mean** and **standard deviation** of `CO(GT)` using both:
- Pandas
- NumPy

In [63]:
# your Code Here
import numpy as np

df['CO(GT)'] = pd.to_numeric(df['CO(GT)'], errors='coerce')

co = df['CO(GT)']

# Pandas
pd_mean = co.mean()           
pd_std  = co.std(ddof=1)     

# NumPy 
np_mean = np.nanmean(co.values)
np_std  = np.nanstd(co.values, ddof=1)

print("Pandas  -> mean:", pd_mean, "std:", pd_std)
print("NumPy   -> mean:", np_mean, "std:", np_std)

Pandas  -> mean: -34.207523778989 std: 77.65717034682943
NumPy   -> mean: -34.207523778989 std: 77.6571703468316


### Q4. Absolute humidity (AH) distribution  
Compute the **min**, **median**, and **max** of `AH` using Pandas.  

Do you notice an issue in the values?  
If you think that there are values that are problematic, replace them with the median of the column and print the same three statistics after that.


In [64]:
# your Code Here
import numpy as np
import pandas as pd

df['AH'] = pd.to_numeric(df['AH'], errors='coerce')

before = df['AH'].agg(['min', 'median', 'max'])
print("Before:\n", before)

invalid = df['AH'] <= -200            
median_valid = df.loc[~invalid, 'AH'].median()
df.loc[invalid, 'AH'] = median_valid

after = df['AH'].agg(['min', 'median', 'max'])
print("\nAfter replacing invalid values with the median:\n", after)

Before:
 min      -200.0000
median      0.9768
max         2.2310
Name: AH, dtype: float64

After replacing invalid values with the median:
 min       0.1847
median    0.9954
max       2.2310
Name: AH, dtype: float64


### Q5. Humidity bands
Create a new column `humidity_band` using `RH`:
- `'dry'` if `RH < 30`
- `'comfortable'` if `30 <= RH <= 60`
- `'humid'` if `RH > 60`

Then show the **count** of each category.

In [65]:
# your Code Here
import numpy as np
import pandas as pd

df['RH'] = pd.to_numeric(df['RH'], errors='coerce')

df['humidity_band'] = np.select(
    [
        df['RH'] < 30,
        (df['RH'] >= 30) & (df['RH'] <= 60),
        df['RH'] > 60
    ],
    ['dry', 'comfortable', 'humid'],
    default=pd.NA
)

print(df['humidity_band'].value_counts())

humidity_band
comfortable    4929
humid          2633
dry            1795
Name: count, dtype: int64


### Q6. Compute the Average 'CO(GT)' for Humid Conditions  

Using the `'humidity_band'` column created above, filter the dataset for rows labeled `'humid'` and compute the **average value of `'CO(GT)'`** for these observations.  

Format the output to 4 decimal places for better readability and precision.

In [66]:
# your Code Here
import pandas as pd

df['CO(GT)'] = pd.to_numeric(df['CO(GT)'], errors='coerce')

df.loc[df['CO(GT)'] <= -200, 'CO(GT)'] = pd.NA

mean_humid = df.loc[df['humidity_band'] == 'humid', 'CO(GT)'].mean()

print(f"Average CO(GT) for humid conditions: {mean_humid:.4f}")

Average CO(GT) for humid conditions: 2.2323


### Q7. Retrieve and sort array by a specific column
Create a NumPy array from the columns `[T, RH, AH]` (in this order), then sort the array by the **third column (`AH`)** ascending. Show the first 5 rows.

In [68]:
# your Code Here
import numpy as np
import pandas as pd

cols = ['T', 'RH', 'AH']

tmp = (df[cols]
       .apply(pd.to_numeric, errors='coerce')
       .replace(-200, np.nan)
       .dropna())

arr = tmp.to_numpy()
arr_sorted = arr[np.argsort(arr[:, 2])]

print(arr_sorted[:5])

[[ 0.     29.7     0.1847]
 [11.8    13.5     0.1862]
 [ 0.2    30.2     0.191 ]
 [-0.1    31.9     0.1975]
 [12.2    14.      0.1988]]


### Q8. Normalized moisture index

Using the NumPy array you built above (**Do not change it**):  

1. Using Numpy, **Convert RH to a fraction** (0–1 scale) by dividing it by 100 and save it to another array `RH_frac`.
2. Using Numpy, **Compute a normalized moisture index** by dividing `AH` by `RH_frac`. This almost computes the amount of absolute humidity per unit of relative humidity.

Print the first 10 values of this new array and then **store** the result in the original DataFrame as a new column `'moisture_index'`.

In [70]:
# your Code Here
import numpy as np
import pandas as pd

cols = ['T', 'RH', 'AH']
tmp = (df[cols].apply(pd.to_numeric, errors='coerce').replace(-200, np.nan).dropna())

try:
    arr
except NameError:
    arr = tmp.to_numpy()

RH_frac = arr[:, 1] / 100.0
moisture_index = np.divide(arr[:, 2], RH_frac, out=np.full(arr.shape[0], np.nan, dtype=float), where=RH_frac != 0)

df.loc[tmp.index, 'moisture_index'] = moisture_index
print(df['moisture_index'].head(10).to_numpy())

[1.54969325 1.52096436 1.38925926 1.31116667 1.32348993 1.32567568
 1.33855634 1.28366667 1.28107203 1.2486711 ]


### Q9. Temperature profile for high moisture index  

Using Numpy only, and the `moisture_index` values you computed earlier:  

1. Find the **median** of `moisture_index`.  
2. Filter `tri_array` to include only rows where `moisture_index` is above this median.  
3. Compute and print the **mean temperature** for this high-moisture group using only NumPy.

Format the output to 4 decimal places for better readability and precision.

In [42]:
# your Code Here
import numpy as np

tri_array = arr
mi_median = np.nanmedian(moisture_index)
mask = moisture_index > mi_median
high_group = tri_array[mask]
mean_temp = np.nanmean(high_group[:, 0])

print(f"Median moisture_index: {mi_median:.4f}")
print(f"Mean temperature (moisture_index > median): {mean_temp:.4f}")


Median moisture_index: 1.9457
Mean temperature (moisture_index > median): 25.2345


### Q10. Percentile-based filtering
Compute:
- the **85th percentile** of `C6H6(GT)` (benzene), and
- the **25th percentile** of `RH`.

Filter and return rows where `C6H6(GT)` is **above** its 85th percentile **and** `RH` is **below** its 25th percentile. Show the number of rows and the first 5 matches.


In [41]:
# your Code Here
import numpy as np
import pandas as pd

for col in ['C6H6(GT)', 'RH']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

c6 = df['C6H6(GT)'].replace(-200, np.nan)
rh = df['RH'].replace(-200, np.nan)

p85_c6 = c6.quantile(0.85)
p25_rh = rh.quantile(0.25)

mask = (c6 > p85_c6) & (rh < p25_rh)
subset = df.loc[mask]

print(f"85th percentile of C6H6(GT): {p85_c6:.4f}")
print(f"25th percentile of RH:      {p25_rh:.4f}")
print(f"Matching rows: {len(subset)}")
display(subset.head(5))

85th percentile of C6H6(GT): 17.6000
25th percentile of RH:      35.8000
Matching rows: 288


Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
120  15/03/2004  18.00.00     6.1       1917.0     471.0      32.1   
137  16/03/2004  11.00.00     4.1       1571.0     327.0      20.0   
138  16/03/2004  12.00.00     3.3       1452.0     283.0      18.3   
139  16/03/2004  13.00.00     4.0       1579.0     366.0      22.3   
140  16/03/2004  14.00.00     3.8       1466.0     318.0      20.4   

     PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
120         1601.0    314.0         631.0    162.0        2447.0       1843.0   
137         1297.0    314.0         730.0    162.0        1973.0       1729.0   
138         1250.0    217.0         776.0    154.0        1868.0       1583.0   
139         1359.0    252.0         724.0    161.0        1998.0       1671.0   
140         1309.0    263.0         773.0    161.0        1897.0       1491.0   

        T    RH      AH  PT08.S1_noisy  
120  22.5  35.4  0.9547    1954.642553  
137  21.4  33.3  0.8417    1550.170124  
138  24.4  27.4  0.8231    1491.600671  
139  25.3  26.1  0.8264    1469.693849  
140  25.8  23.2  0.7589    1316.874241

### Q11. Simulate Sensor Measurement Noise and Analyze the Effect  

Simulate **normally distributed measurement noise** with a mean of `0` and a standard deviation of `100` (in raw sensor units). Then:  

- Use **NumPy** to generate the noise.  
- Use **Pandas** to add this noise to the `'PT08.S1(CO)'` column and store the result in a new column `'PT08.S1_noisy'`.  
- Print the **mean** and **standard deviation** of both `'PT08.S1(CO)'` and `'PT08.S1_noisy'` to observe the impact of the simulated noise.  

Observe how the added noise affects the distribution, particularly the spread (**standard deviation**). Format all printed values to **4 decimal places** using `.4f`.  


In [39]:
# your Code Here
import numpy as np
np.random.seed(0)
import pandas as pd

s = pd.to_numeric(df['PT08.S1(CO)'], errors='coerce')
noise = np.random.normal(0, 100, len(s))
df['PT08.S1_noisy'] = s + noise

print(f"PT08.S1(CO)   -> mean: {s.mean():.4f}, std: {s.std():.4f}")
print(f"PT08.S1_noisy -> mean: {df['PT08.S1_noisy'].mean():.4f}, std: {df['PT08.S1_noisy'].std():.4f}")

PT08.S1(CO)   -> mean: 1048.9901, std: 329.8327
PT08.S1_noisy -> mean: 1046.8703, std: 345.1911


So, your NumPy import at the top of the notebook should now look like this:

```python
import numpy as np
np.random.seed(0)
